Repository khujista-01/SHARKY-SOEN341_Project_F24, pull requests merged in 2024-10, with the labels that each got.

#43 Role-Based Login, CSV Team Creation, Layout Adjustments, and CSS Enhancements
  Sharky/package-lock.json
  Sharky/package.json
  Sharky/src/pages/ForgotPw.js
  Sharky/src/pages/Homepage.js
  Sharky/src/pages/LogIn.js
  Sharky/src/pages/ResetPW.js
  Sharky/src/pages/SignUp.js
  Sharky/src/pages/TeamManagement.js
  Sharky/src/style.css
Labels: bug, documentation, enhancement

#50 Enhancement: Add Logo to Header and Enable Scrollbar
  Sharky/public/logo.png
  Sharky/src/pages/ForgotPw.js
  Sharky/src/pages/LogIn.js
  Sharky/src/pages/ResetPW.js
  Sharky/src/pages/SignUp.js
  Sharky/src/pages/TeamManagement.js
  Sharky/src/style.css
Labels: bug, enhancement

#55 Enhanced team view. Add team and member selection
  Sharky/src/pages/ShowTeams.js
Labels: enhancement

#61 Hala-updates: Updates to Fix Issues and Improve Functionality
  Sharky/package-lock.json
  Sharky/package.json
  Sharky/src/App.js
  Sharky/src/components/protectedRoute.js
  Sharky/src/pages/Assessment.js
  Sharky/src/pages/HandleTeamInstructure.js
  Sharky/src/pages/Homepage.js
  Sharky/src/pages/LogIn.js
  Sharky/src/pages/Logout.js
  Sharky/src/pages/ShowTeams.js
  Sharky/src/pages/SignUp.js
  Sharky/src/pages/TeamManagement.js
  Sharky/src/pages/Welcomepage.js
  Sharky/src/pages/main.js
  Sharky/src/style.css
Labels: bug, enhancement

#72 Create Sharky_Sprint2_meeting8_Oct24.md
  Meeting Minutes/Sharky_Sprint2_meeting7_Oct24.md
Labels: documentation

#81 Implement Continuous Integration (CI) Pipeline for Automated Testing
  .github/workflows/ci.yml
Labels: CI/CD, automation

#82 Revert "Implement Continuous Integration (CI) Pipeline for Automated …
  .github/workflows/ci.yml
Labels: bug, CI/CD

#85 Fixes hlbels/SHARKY-SOEN341_Project_F24#77
  Sharky/package-lock.json
  Sharky/src/pages/ShowTeams.js
  Sharky/src/style.css
Labels: enhancement

#90 Updating and fixing the acceptance test for Forgot Password
  Sharky/package-lock.json
  Sharky/package.json
  Sharky/src/test/ForgotPw.test.js
Labels: bug, test

#91 User Acceptance Test for Login Component
  Sharky/src/test/LogIn.test.js
Labels: test

#97 Create Meeting Minute Oct30th
  Meeting Minutes/Meeting Minute Oct30th
Labels: documentation
