Repository khujista-01/SHARKY-SOEN341_Project_F24, pull requests merged in 2024-11, with the labels that each got.

#98 Update README.md-Updating repository URL
  README.md
Labels: documentation

#102 Implementation of the Conceptual Contribution Assessment page. Issue #99
  Sharky/src/App.js
  Sharky/src/pages/Assessment.js
  Sharky/src/pages/ConceptualAssessment.js
  Sharky/src/pages/main.js
Labels: enhancement

#103 Rename Meeting Minutes/Meeting Minute Oct30th to Sharky_Sprint3_meeting8_Oct30.md
  Sharky_Sprint3_meeting8_Oct30.md
Labels: documentation

#104 Rename Sharky_Sprint3_meeting8_Oct30.md to Meeting Minutes/Sharky_Sprint3_meeting8_Oct30.md
  Meeting Minutes/Sharky_Sprint3_meeting8_Oct30.md
Labels: documentation

#108 Change to the Supabase URL and key. Fixes #107
  Sharky/src/client.js
Labels: backend

#109 Update README.md
  README.md
Labels: documentation
